/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    AppLoader: typeof import('./src/components/AppLoader.vue')['default']
    CalendarCard: typeof import('./src/components/CalendarCard.vue')['default']
    CalendarDays: typeof import('./src/components/CalendarDays.vue')['default']
    CookingInstructions: typeof import('./src/components/CookingInstructions.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MealPlanner: typeof import('./src/components/MealPlanner.vue')['default']
    RecipeRating: typeof import('./src/components/RecipeRating.vue')['default']
    RecipeSearch: typeof import('./src/components/RecipeSearch.vue')['default']
    RecipesList: typeof import('./src/components/RecipesList.vue')['default']
    RecipeTable: typeof import('./src/components/RecipeTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
